/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as The24RouteImport } from './routes/the-24'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MediaRouteImport } from './routes/media'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FranchisesRouteImport } from './routes/franchises'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FranchisesSlugRouteImport } from './routes/franchises.$slug'

const The24Route = The24RouteImport.update({
  id: '/the-24',
  path: '/the-24',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchisesRoute = FranchisesRouteImport.update({
  id: '/franchises',
  path: '/franchises',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchisesSlugRoute = FranchisesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FranchisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRoute
  '/membership': typeof MembershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/store': typeof StoreRoute
  '/the-24': typeof The24Route
  '/franchises/$slug': typeof FranchisesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRoute
  '/membership': typeof MembershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/store': typeof StoreRoute
  '/the-24': typeof The24Route
  '/franchises/$slug': typeof FranchisesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/franchises': typeof FranchisesRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/media': typeof MediaRoute
  '/membership': typeof MembershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/store': typeof StoreRoute
  '/the-24': typeof The24Route
  '/franchises/$slug': typeof FranchisesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/franchises'
    | '/investors'
    | '/media'
    | '/membership'
    | '/sitemap.xml'
    | '/sponsors'
    | '/store'
    | '/the-24'
    | '/franchises/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/franchises'
    | '/investors'
    | '/media'
    | '/membership'
    | '/sitemap.xml'
    | '/sponsors'
    | '/store'
    | '/the-24'
    | '/franchises/$slug'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/contact'
    | '/franchises'
    | '/investors'
    | '/media'
    | '/membership'
    | '/sitemap.xml'
    | '/sponsors'
    | '/store'
    | '/the-24'
    | '/franchises/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FranchisesRoute: typeof FranchisesRouteWithChildren
  InvestorsRoute: typeof InvestorsRoute
  MediaRoute: typeof MediaRoute
  MembershipRoute: typeof MembershipRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  StoreRoute: typeof StoreRoute
  The24Route: typeof The24Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-24': {
      id: '/the-24'
      path: '/the-24'
      fullPath: '/the-24'
      preLoaderRoute: typeof The24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchises': {
      id: '/franchises'
      path: '/franchises'
      fullPath: '/franchises'
      preLoaderRoute: typeof FranchisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchises/$slug': {
      id: '/franchises/$slug'
      path: '/$slug'
      fullPath: '/franchises/$slug'
      preLoaderRoute: typeof FranchisesSlugRouteImport
      parentRoute: typeof FranchisesRoute
    }
  }
}

interface FranchisesRouteChildren {
  FranchisesSlugRoute: typeof FranchisesSlugRoute
}

const FranchisesRouteChildren: FranchisesRouteChildren = {
  FranchisesSlugRoute: FranchisesSlugRoute,
}

const FranchisesRouteWithChildren = FranchisesRoute._addFileChildren(
  FranchisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FranchisesRoute: FranchisesRouteWithChildren,
  InvestorsRoute: InvestorsRoute,
  MediaRoute: MediaRoute,
  MembershipRoute: MembershipRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  StoreRoute: StoreRoute,
  The24Route: The24Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
